### ISSUE TITLE
High level design

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/hyrax-batch_ingest#12]
### Description
We need a diagram that details the flow of the batch interface in a technical way, that includes decisions made.

### Tasks
  - [x] Dev meeting scheduled for high level design.
  - [x] Create preliminary diagram to bring to meeting.
  - [x] Dev meeting held for high level design.

### Done Looks Like
  - [x] A diagram of the system components and how data moves through them.
  - [x] Diagram is placed in a shared location. 
  - [x] The team signs off on the diagram
  - [x] Tickets for defining the APIs for each component (input and output).
