### ISSUE TITLE
Stubbing out Interfaces

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/hyrax-batch_ingest#33]
### Description
Groundwork for implementing the diagram developed: https://iu.app.box.com/file/320290778323

### Done Looks Like
- Stub out interface
- Stub out tests for interface

## TODO:
 - [x] tests for routing
    - [x] `/batches` (batch list)
    - [x] `/batches/[batch_id]` (batch detail)
    - [x] `batches/[batch_id]/[batch_item_id]`  (batch item details)

**Comment by mcwhitaker** [comment]
This will be only the first pass and feedback from other developers coming over and over after this ticket is complete.

**Comment by cjcolvar** [comment]
@afred I'm pretty sure you did the todos in #37.  What else needs to be done for this ticket?
